### ISSUE TITLE
Error when using Liquigraph dependencies and Stanford NLP dependencies

### ISSUE THREAD

**Issue by wanzzzone** [fbiville/liquigraph#154]
I've been trying to implement liquigraph on my project. I'm using this example https://github.com/fbiville/liquigraph-spring-boot-example. The example runs fine until I tried to add two dependencies from Stanford NLP:

```
    <dependency>
        <groupId>edu.stanford.nlp</groupId>
        <artifactId>stanford-corenlp</artifactId>
        <version>3.6.0</version>
    </dependency>
    <dependency>
        <groupId>edu.stanford.nlp</groupId>
        <artifactId>stanford-corenlp</artifactId>
        <version>3.6.0</version>
        <classifier>models</classifier>
    </dependency>
```

After I added these two dependencies, I got this error :
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquigraph' defined in class path resource [org/liquigraph/spring/starter/LiquigraphAutoConfiguration$LiquigraphConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: 
cvc-elt.1: Cannot find the declaration of element 'changelog'.
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
at org.liquigraph.examples.spring.SampleController.main(SampleController.java:48) [classes/:na]

Caused by: java.lang.IllegalArgumentException: 
    cvc-elt.1: Cannot find the declaration of element 'changelog'.
    at org.liquigraph.core.io.xml.ChangelogParser.parseChangelog(ChangelogParser.java:67) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
    at org.liquigraph.core.io.xml.ChangelogParser.parse(ChangelogParser.java:59) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
    at org.liquigraph.core.api.MigrationRunner.parseChangesets(MigrationRunner.java:87) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
    at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:68) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
    at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
    at org.liquigraph.spring.SpringLiquigraph.afterPropertiesSet(SpringLiquigraph.java:52) ~[liquigraph-spring-boot-starter-3.0.2-SNAPSHOT.jar:na]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
    ... 16 common frames omitted
```

This is the mvn dependency:tree before i add stanford nlp: 
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Example integration with Spring Boot 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ liquigraph-spring -
--
[INFO] org.liquigraph.examples:liquigraph-spring:jar:1.0-SNAPSHOT
[INFO] +- com.zaxxer:HikariCP:jar:2.4.7:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] +- org.liquigraph:liquigraph-spring-boot-starter:jar:3.0.2-SNAPSHOT:compi
le
[INFO] |  +- org.liquigraph:liquigraph-core:jar:3.0.2-SNAPSHOT:compile
[INFO] |  |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  |  \- org.neo4j:neo4j-jdbc-driver:jar:3.0.1:runtime
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:1.4.2.RELEAS
E:compile
[INFO] |     \- org.springframework.boot:spring-boot:jar:1.4.2.RELEASE:compile
[INFO] \- org.springframework.boot:spring-boot-starter-web:jar:1.4.2.RELEASE:com
pile
[INFO]    +- org.springframework.boot:spring-boot-starter:jar:1.4.2.RELEASE:comp
ile
[INFO]    |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.4.2.R
ELEASE:compile
[INFO]    |  |  +- ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO]    |  |  |  \- ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO]    |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.21:compile
[INFO]    |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile
[INFO]    |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.21:compile
[INFO]    |  +- org.springframework:spring-core:jar:4.3.4.RELEASE:compile
[INFO]    |  \- org.yaml:snakeyaml:jar:1.17:runtime
[INFO]    +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.4.2.RELEA
SE:compile
[INFO]    |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.6:compile
[INFO]    |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.6:compile
[INFO]    |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.6:compile

[INFO]    +- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO]    |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO]    |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO]    |  \- com.fasterxml:classmate:jar:1.3.3:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.4:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.4:compile

[INFO]    |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.4:compile
[INFO]    +- org.springframework:spring-web:jar:4.3.4.RELEASE:compile
[INFO]    |  +- org.springframework:spring-aop:jar:4.3.4.RELEASE:compile
[INFO]    |  +- org.springframework:spring-beans:jar:4.3.4.RELEASE:compile
[INFO]    |  \- org.springframework:spring-context:jar:4.3.4.RELEASE:compile
[INFO]    \- org.springframework:spring-webmvc:jar:4.3.4.RELEASE:compile
[INFO]       \- org.springframework:spring-expression:jar:4.3.4.RELEASE:compile
[INFO] ------------------------------------------------------------------------
```

This is the mvn dependency:tree after i add stanford nlp: 
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Example integration with Spring Boot 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ liquigraph-spring -
--
[INFO] org.liquigraph.examples:liquigraph-spring:jar:1.0-SNAPSHOT
[INFO] +- com.zaxxer:HikariCP:jar:2.4.7:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] +- org.liquigraph:liquigraph-spring-boot-starter:jar:3.0.2-SNAPSHOT:compi
le
[INFO] |  +- org.liquigraph:liquigraph-core:jar:3.0.2-SNAPSHOT:compile
[INFO] |  |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  |  \- org.neo4j:neo4j-jdbc-driver:jar:3.0.1:runtime
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:1.4.2.RELEAS
E:compile
[INFO] |     \- org.springframework.boot:spring-boot:jar:1.4.2.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.4.2.RELEASE:com
pile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.4.2.RELEASE:comp
ile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.4.2.R
ELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO] |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.21:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile
[INFO] |  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.21:compile
[INFO] |  |  +- org.springframework:spring-core:jar:4.3.4.RELEASE:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.17:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.4.2.RELEA
SE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.6:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.6:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.6:compile

[INFO] |  +- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.4:compile

[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.4:compile
[INFO] |  +- org.springframework:spring-web:jar:4.3.4.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:4.3.4.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:4.3.4.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-context:jar:4.3.4.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.3.4.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:4.3.4.RELEASE:compile
[INFO] +- edu.stanford.nlp:stanford-corenlp:jar:3.6.0:compile
[INFO] |  +- com.io7m.xom:xom:jar:1.2.10:compile
[INFO] |  |  +- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  |  +- xerces:xercesImpl:jar:2.8.0:compile
[INFO] |  |  \- xalan:xalan:jar:2.7.0:compile
[INFO] |  +- joda-time:joda-time:jar:2.9.5:compile
[INFO] |  +- de.jollyday:jollyday:jar:0.4.7:compile
[INFO] |  |  \- javax.xml.bind:jaxb-api:jar:2.2.7:compile
[INFO] |  +- com.googlecode.efficient-java-matrix-library:ejml:jar:0.23:compile
[INFO] |  \- javax.json:javax.json-api:jar:1.0:compile
[INFO] \- edu.stanford.nlp:stanford-corenlp:jar:models:3.6.0:compile
[INFO] ------------------------------------------------------------------------
```
This is my changelog file (Please rename extension to .xml):
[changelog.txt](https://github.com/fbiville/liquigraph/files/709905/changelog.txt)

**Comment by fbiville** [comment]
Thanks for the report.

Basically, Xerces is in conflict with JAXB.

Doing this:
```xml
<dependency>
        <groupId>edu.stanford.nlp</groupId>
        <artifactId>stanford-corenlp</artifactId>
        <version>3.6.0</version>
        <exclusions>
            <exclusion>
                <groupId>xerces</groupId>
                <artifactId>xercesImpl</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
```

seems to avoid the error. 

However, does Stanford NLP remain usable without Xerces? I'm not sure. 

Can you try this and use some code from that lib to confirm it works or not?

**Comment by wanzzzone** [comment]
Yes confirmed can run if i exclude xerces. 
So far still runs fine but i don't know if i will use that xerces or not. 
Can you please enlighten me what the usage of xerces? and why it conflict with liquigraph? 
Can this issue solved without  i need to exclude the xerces? 
Thank you

**Comment by fbiville** [comment]
Basically, Liquigraph rely on the default JAXB implementation shipped with the Java Development Kit to deserialize XML changelogs into Java objects.

Xerces is a concurrent library that also implements the JAXB specification.

What happens is that the default JAXB implementation pulled by Liquigraph globally registers its XML parser, so does Xerces. In the end, Xerces overwrites the other parser and it wreaks havoc on Liquigraph.

This is a common issue. I'm not sure what's the best course of action is. I read that excluding Xerces impl should be fine, although, I agree with you @wanzzzone, it is not ideal.

Maybe @mvitz or @fpavageau have better ideas.

For the time being I'd stick with the exclusion approach.

**Comment by mvitz** [comment]
In fact I think we don't have much chances here to fix this on our side.

Xerces which is transitive included in your case is used as the JAXB implementation and it seems this version of Xerces does not have all the features required by Liquigraph.

All I found is the documentation for XOM (which includes Xerces):
> Java 1.3 and earlier do not have a built-in XML parser so in these environments 
> you'll also need to install XOM's supporting libraries. 
> These include xalan.jar, xercesImpl.jar, and xml-apis.jar, 
> and are found in the lib directory. The versions shipped with XOM 
> are quite a bit faster and less buggy than the ones bundled with the JDK, 
> so you may well want to use them even in Java 1.4 and later. For example,
> 
> $ java -classpath xom-samples.jar:xom-1.2.10.jar:lib/xml-apis.jar:lib/xercesImpl.jar:lib/xalan.jar nu.xom.samples.PrettyPrinter filename.xml
> 
> You could leave out xalan.jar if you don't use any of the classes in
> nu.xom.xslt. junit.jar is only used for testing, and is
> not needed for normal operation of XOM.

So it may be fine to exclude all of these as the current JDKs ship newer versions and everything should work.

**Comment by wanzzzone** [comment]
Okay thank you for the answer. I think i stick to this solution :).
