### ISSUE TITLE
[Core] Support Neo4j 2.2.0

### ISSUE THREAD

**Issue by fbiville** [fbiville/liquigraph#36]
Currently failing:

```
instantiates_a_remote_graph_database(org.liquigraph.core.writer.GraphJdbcConnectorTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/neo4j/graphdb/mockfs/EphemeralFileSystemAbstraction
	at org.neo4j.test.ImpermanentGraphDatabase.createFileSystemAbstraction(ImpermanentGraphDatabase.java:201)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.create(InternalAbstractGraphDatabase.java:415)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGraphDatabase.java:321)
	at org.neo4j.kernel.EmbeddedGraphDatabase.<init>(EmbeddedGraphDatabase.java:59)
	at org.neo4j.test.ImpermanentGraphDatabase.<init>(ImpermanentGraphDatabase.java:139)
	at org.neo4j.test.ImpermanentGraphDatabase.<init>(ImpermanentGraphDatabase.java:123)
	at org.neo4j.test.ImpermanentGraphDatabase.<init>(ImpermanentGraphDatabase.java:97)
	at org.neo4j.test.ImpermanentGraphDatabase.<init>(ImpermanentGraphDatabase.java:88)
	at org.neo4j.test.ImpermanentGraphDatabase.<init>(ImpermanentGraphDatabase.java:65)
	at org.neo4j.jdbc.internal.embedded.EmbeddedDatabases.defaultImpermanentDb(EmbeddedDatabases.java:104)
	at org.neo4j.jdbc.internal.embedded.EmbeddedDatabases.createDatabase(EmbeddedDatabases.java:73)
	at org.neo4j.jdbc.internal.embedded.EmbeddedDatabases.createExecutor(EmbeddedDatabases.java:109)
	at org.neo4j.jdbc.Driver.createExecutor(Driver.java:146)
	at org.neo4j.jdbc.internal.Neo4jConnection.createExecutor(Neo4jConnection.java:131)
	at org.neo4j.jdbc.internal.Neo4jConnection.<init>(Neo4jConnection.java:79)
	at org.neo4j.jdbc.internal.Connections$4.doCreate(Connections.java:65)
	at org.neo4j.jdbc.internal.Connections.create(Connections.java:80)
	at org.neo4j.jdbc.Driver.connect(Driver.java:80)
	at org.neo4j.jdbc.Driver.connect(Driver.java:42)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.liquigraph.core.writer.GraphJdbcConnector.connect(GraphJdbcConnector.java:16)
	at org.liquigraph.core.writer.GraphJdbcConnectorTest.instantiates_a_remote_graph_database(GraphJdbcConnectorTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: org.neo4j.graphdb.mockfs.EphemeralFileSystemAbstraction
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more
```

**Comment by owetterau** [comment]
I am running into this issue, too...

**Comment by anragab** [comment]
Same problem

**Comment by fbiville** [comment]
I think I has this problem with some 2.2 release candidates.
I'll try finding the thread on Neo4j Google Group where some workarounds were described.

**Comment by fbiville** [comment]
This is the conversation I had.
Currently figuring out how to include neo4j-io for Neo4j 2.x builds.

**Comment by fbiville** [comment]
Finally fixed :)
